### ISSUE TITLE
Typescript 5? 😁

### ISSUE THREAD

**Issue by Kegulf** [IanVS/ts-module-resolution-examples#6]
I loved your video (deep dive into TS modules), really good stuff.

Any chance you have something like this for TS 5? 😅

**Comment by IanVS** [comment]
I'm glad it's been useful to you.  I did do a set of videos detailing the changes to module resolution in 5.x releases, but I don't think they've been published yet.  I'll see if I can get ahold of them somehow.

**Comment by IanVS** [comment]
Ah, I was wrong, they are indeed published, here they are:

- [TypeScript 5.0 - Resolution Customization Flags](https://youtu.be/uKcfxI84xPc?si=4C8Fa1kGB-roejUP) 
- [TypeScript 5.0 - `--moduleResolution bundler`](https://youtu.be/wfCRQF-HxwY?si=E28B1MipgyElA8QS)
- [TypeScript 5.1 - `typeRoots` Are Consulted In Module Resolution](https://youtu.be/Z5Qk6z9RK4s?si=-mPoX2bmxp0ey5oK)
- [TypeScript 5.1 - Explicit `typeRoots` Disables Upward Walks for node_modules/@types](https://youtu.be/avVimJ1gdNA?si=zm-lwIQHCNo3JA-j)
- [TypeScript 5.2 - `module` and `moduleResolution` Must Match Node.js Settings](https://youtu.be/j3OUn0iw4k8?si=Km4-xA1FkmpW6gaj)
- [TypeScript 5.2 - Type-Only Import Paths + TypeScript Implementation File Extensions](https://youtu.be/ZwNIsSmk-Ks?si=XGQl-BmzXYOGUhYF)
